version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    environment:
      DATABASE_URL: postgres://myuser:mysecretpassword@postgres:5432/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres-data:
